include:

  - board: nice_nano_v2 
    shield: corne_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset

