include:

  - board: nice_nano_v2 
    shield: kyria_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: kyria_right nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: settings_reset
